internal object Versions {
    const val KOTLIN = "1.6.10"
    const val KOTLIN_STDLIB = "1.4.32"
    const val ANDROID_BUILD_TOOLS = "7.0.4"
    const val HIT_PLUGIN = "2.39"
    const val LIFECYCLE = "2.4.1"
    const val MATERIAL = "1.6.0"
    const val CORE_KTX = "1.8.0"
    const val ACTIVITY_KTX = "1.5.1"
    const val APP_COMPAT = "1.4.0"
    const val COROUTINES = "1.6.4"
    const val RETROFIT = "2.9.0"
    const val GSON = "2.8.6"
    const val COIL = "2.2.0"
    const val MULTIDEX = "2.0.1"
    const val HILT_ANDROID = "2.43.2"
    const val HILT_COMPILER = "2.43.2"
    const val JUNIT = "4.12"
    const val EXT_JUNIT = "1.1.3"
    const val ESPRESSO_CORE = "3.4.0"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val PAGING_VERSION = "3.2.0-alpha02"
}